### ISSUE TITLE
🌟New member role

### ISSUE THREAD

**Issue by probablyArth** [selfdevs/watcher#4]
refer this https://github.com/selfdevs/watcher/issues/3#issuecomment-1072401647

**Comment by probablyArth** [comment]
Are you still working on this? @Some-CodingGuy lmao

**Comment by Some-CodingGuy** [comment]
We decided it wasn't necessay anymore, since discord already had the green leaf thing for newcomers. I don't know if that was enough tho. Should this still be done then?

**Comment by probablyArth** [comment]
no the leaf thing does it I think!
